### PR TITLE
fix undefined reference error in Component.js

### PR DESCRIPTION
**Pull request by wujjpp**
## Description
before access newInput.$global， we should judge if it is undefined or not

_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the project's open source license and warrant that you have the legal authority to do so._

### CODE REVIEW

**Comment by austinkelleher** [comment]
The only time I think this would happen is if you were setting `component.input = null`. Is that your use case?

**Comment by wujjpp** [comment]
@austinkelleher YES

Scenario:

SSR

// file structure


app-sorter was rendered at server side, by it's state. The state data is from input, at client side app-sorter was manage state by it's self and emit changed event to parent component.  parent component handle event for fetching data and set it's state for other components(such as list, paginator and etc)

the problem was: after mount at client side, the error occurs.

components/app/index.marko


components/app/component.js


components/app-sorter/index.marko


components/app-sorter/component.js

**Comment by wujjpp** [comment]
@austinkelleher YES

Scenario:  we receive `sorter` data from query string and initialize app-sorter component.

1. server router
[https://github.com/wujjpp/marko-starter-kit/blob/test-issue/src/routes/test-issue/index.js#L5-L18](url)


2. components/app/index.marko
https://github.com/wujjpp/marko-starter-kit/blob/test-issue/src/routes/test-issue/components/app/index.marko#L1-L5


3. components/app-sorter/index.marko
[https://github.com/wujjpp/marko-starter-kit/blob/test-issue/src/routes/test-issue/components/app-sorter/index.marko#L1-L8](url)


4. components/app-sorter/component.js
[https://github.com/wujjpp/marko-starter-kit/blob/test-issue/src/routes/test-issue/components/app-sorter/component.js#L1-L18](url)


5. undefined error


6. normal

**Comment by austinkelleher** [comment]
Thanks for taking the time to investigate this issue and submitting a fix! Published `marko@4.4.28` with this fix.

**Pull request merged**
