### PR TITLE
perf: minify runtime comments, remove unnecessary attr quotes

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description

Working toward: https://github.com/marko-js/marko/issues/1432

## Checklist:

This PR removes unnecessary characters from the html output where possible:

1. Removes `--` from comments since all tested browsers do not require them, for example `<!M>` is a treated valid comment.
2. Removes unnecessary quotes around attributes where possible. Any attribute that doesn't contain `'">` or any space characters can have the quotes removed. Technically the [spec](http://w3c.github.io/html-reference/syntax.html#syntax-attr-unquoted) says that `=`, `<` and backticks also need to be escaped, however browsers appear happy to ignore that. The implementation could do better by ensuring the minimum number of escapes by switching between single or double quotes, but for performance reasons instead it will immediately use single quotes when the first double quote is found which works well for most cases.

- [x] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [ ] I have updated/added documentation affected by my changes.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by redonkulus** [comment]
@DylanPiercey FYI, this ended up breaking marko snapshots locally since all the attrs were removed. I thought it was a bug in my code somewhere. It probably didn't warrant a major version bump, but can definitely cause builds to fail until updated.

**Comment by DylanPiercey** [comment]
@redonkulus at the end of the day a snapshot test is going to capture many implementation details of Marko that we don't consider a "public api". We'd expect snapshots to need updating across many releases in Marko 4. The point of snapshot tests though are not to assert that something is working, but to let you know that something has changed. I think developers having to update snapshots during changes like this is acceptable.

**Comment by tigt** [comment]
Removing the `--` delimiters from comments produces a lot of noisy errors/warnings from tools like the HTML validator for our automated & manual checks. Not sure how much that matters to you.

**Comment by mlrawlings** [comment]
@tigt We may need to revisit that... 

It technically violates the spec but we tested it in Safari, FF, Chrome, Edge, and IE and it parses as expected.

**Comment by tigt** [comment]
Yeah, I’m not aware of any HTML parsers that would refuse to work with it.

**Comment by DylanPiercey** [comment]
It's tricky. Basically the shorter comments are objectively better since it's just less rendered and shipped code, but tools are going to complain.

I think Marko needs to take a stance on if it is more valuable to have output which linters like, or that is more performant / smaller.

**Comment by mlrawlings** [comment]
We're reverting the comment change for now.  We'll revisit this in the future.

**Comment by alexnaidovich** [comment]
Is there the way to bring the quotes for attributes' values (that were considered there to be unnecessary) back to the output? There **are** real cases when quotes are necessary. Maybe, are there some configurable options for that?

**Pull request merged**
