### PR TITLE
Fixes #749 #690 - Do not rely on root node having an ID on rerender a…

### LINKED ISSUE #749: Infinite loop into Component.js
https://github.com/marko-js/marko/blob/master/src/components/Component.js#L553

If Component don't have id that place become an infinite loop.

### PR DESCRIPTION
**Pull request by austinkelleher**

### CODE REVIEW

**Comment by mlrawlings** [comment]
@austinkelleher Is this finished? The code change looks good, but the tests don't make any assertions.  Is the idea to just test that no errors are thrown?

**Comment by austinkelleher** [comment]
@mlrawlings Before these changes, using multiple root nodes or style tag at the root would cause an infinite loop on re-render. The tests I wrote ensure that the code does not get stuck in an infinite loop. I'm not sure what the best way to provide meaningful assertion is without writing unit tests for `src/components/Component.js`.

**Comment by mlrawlings** [comment]
Maybe rename `multiple-roots` to `rerender-multiple-roots` and add a comment to the end of the tests so that in the future it's more clear to anyone that might be looking at the test that it is just testing that it rerenders successfully?
```
// The rerender was successful: no error or infinite loop.  Test passes.
```

**Comment by austinkelleher** [comment]
@mlrawlings Good suggestion. I made the changes and squashed. Let me know if you or @patrick-steele-idem have any more suggestions.

**Pull request merged**
