### PR TITLE
Create troubleshooting-streaming.md

### PR DESCRIPTION
**Pull request by tigt**
## Description

Writeup of findings prompted from Discord conversation

## Checklist

- [x] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [x] I have updated/added documentation affected by my changes.
- ~~[ ] I have added tests to cover my changes.~~

### CODE REVIEW

**Comment by mlrawlings** [comment]
This is great! We also should add it to [`structure.json`](https://github.com/marko-js/marko/blob/main/packages/marko/docs/structure.json) so it will show up in the menu on the website.  

I'm wondering if it makes sense to start a new "Troubleshooting" section.

**Comment by tigt** [comment]
What else would go in the Troubleshooting section?

**Comment by mlrawlings** [comment]
Maybe some additional details on common errors and how to resolve them? We already have a few wiki pages for this, for example, https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag

**Comment by tigt** [comment]
Maybe a page that links to that part of the wiki, yeah — I'd rather not
fragment the URLs

**Comment by DylanPiercey** [comment]
@tigt I'm sorry this took so long. We really appreciate the write up here!

**Pull request merged**
