### PR TITLE
Fix regression for no-update on dynamic tag html attributes

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description

Currently if you have a dynamic tag that renders an html element with a `no-update` attribute the attribute will still be updated on new renders. This is a regression from https://github.com/marko-js/marko/blob/master/CHANGELOG.md#4110 (also happens for the include tag since it migrates to the dynamic tag).

This PR passes the properties (containing info like which attributes to preserve) through to the dynamic tag and resolves the issue.

## Checklist:

- [x] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [ ] I have updated/added documentation affected by my changes.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by StarpTech** [comment]
Great catch! Does it fix https://github.com/marko-js/marko/issues/1291 as well ?

**Comment by StarpTech** [comment]
Does it affect components inside dynamic attribute tags? I have the issue that my components are rerendered on client side even with zero state. Also the no-update attribute has zero impact.

**Comment by DylanPiercey** [comment]
@StarpTech this does not solve #1291, been meaning to reply on that. `:no-update` on attributes in Marko does not currently work for components, only html elements. The weirdness is around the "dynamic tags" which can be html elements. In this case there was a regression where the `:no-update` attributes were not honored which this fixes.

**Comment by StarpTech** [comment]
I tried to apply `no-update` on html elements inside components but it gets still rerendered. Can I support you in any way?

**Pull request merged**
