### PR TITLE
Costomize default await timeout

### PR DESCRIPTION
**Pull request by mauricionr**
## Description

Adding option to customize default timeout for await tags

## Motivation and Context

We use await a lot and we need to customize the default await timeout for all await tags and we think this will help us to fix the timeout problem

I've opened an issue asking about this thing #621 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated/added documentation affected by my changes.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by austinkelleher** [comment]
This change looks good to me. Do you mind squashing your commits? Thanks.

**Comment by mauricionr** [comment]
Squashed @austinkelleher 

Thanks :rocket:

**Comment by austinkelleher** [comment]
Actually after given this some more thought, I'm not sure if this is the right approach for globally overriding the default for a component. I don't think the compiler config is the appropriate place for such configuration. Have you considered overriding the `<await>` tag? I'll create an example of this and post a link here.

**Comment by austinkelleher** [comment]
Here's an example of overriding the `await` core tag:

https://github.com/marko-js-samples/override-core-tag

**Comment by mauricionr** [comment]
@austinkelleher i will discuss with my team about override the `<await>` tag, thanks for the demo!

**Comment by austinkelleher** [comment]
@mauricionr In the demo you'll see that I copied part of the `<await>` marko.json. This is my proposed solution for that: https://github.com/marko-js/marko/issues/686

**Comment by mauricionr** [comment]
i saw @austinkelleher, really good proposal, and with this override, we will be able to override any core tag?

**Comment by austinkelleher** [comment]
@mauricionr After speaking with @patrick-steele-idem, we decided that instead of my old approach where I overrode the tag renderer and copying the `<await>` tag's `marko.json` file, we can just override the `await` tag completely and use a transformer to set the `timeout` attribute.

*await-timeout-transformer.js*
```js
module.exports = function(el, context) {
    if (!el.hasAttribute('timeout')) {
        el.setAttributeValue('timeout', context.builder.literal(30000));
    }
}
```

The [override-core-tag](https://github.com/marko-js-samples/override-core-tag) project has been updated with the changes. 

I'm going to go ahead and close this issue. Please let me know if you have any other questions.

**Comment by mauricionr** [comment]
Thanks @austinkelleher and @patrick-steele-idem simpler than the other aproach

**Pull request closed without merging**
