### PR TITLE
Showcase interpolation in shorthand notation

### PR DESCRIPTION
**Pull request by vwong**
## Description

`htmljs-parser` (and thus Marko) is capable of string interpolation in the shorthand notation. We should showcase this!

## Checklist:

- [x] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [x] I have updated/added documentation affected by my changes.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by DylanPiercey — APPROVED** [review]

**Comment by DylanPiercey** [comment]
Awesome, thanks @vwong!

**Comment by vwong** [comment]
@DylanPiercey Is the failing build something I caused?

**Comment by tigt** [comment]
Yeah, the linter is upset about the double space after the period. It went and made that change inside one of my PRs today, oddly.

**Comment by vwong** [comment]
Sorry about that. I'll let you clean that up then.

**Pull request merged**
