### PR TITLE
await tag basic documentation

### PR DESCRIPTION
**Pull request by tcrowe**
## Description
The `await` tag basic implementation and advanced use signature.

## Motivation and Context
I wanted to fill in the basic implementation because it's so handy. If you think this will help users I will also volunteer to document the advanced usage but doing so could take a whole page. Your thoughts?

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated/added documentation affected by my changes.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mindeavor** [comment]
Here's a question I've had and maybe you could add to your documentation: can you use `<await>` within components?

**Comment by tcrowe** [comment]
@mindeavor Yes you can. You can discover a lot about it from here:
https://github.com/marko-js/marko/search?utf8=%E2%9C%93&q=await

**Comment by patrick-steele-idem** [comment]
Thanks for the PR! (sorry for being slow to merge this PR)

We'll be publishing a new version of the site soon.

**Comment by tcrowe** [comment]
You're welcome! 👍

**Pull request merged**
