### PR TITLE
fix nextsibiling error caused by components not being removed from lookup

### LINKED ISSUE #1052: Uncaught TypeError: Cannot read property 'nextSibling' of null
### Details

We have dialog component which is a stateful component. When the dialog is shown and then close, and then shown again, we got an error on browser console which causing any component's browser-side-behaviour stop working at all:

```
Uncaught TypeError: Cannot read property 'nextSibling' of null
    at Component.___forEachNode (Component.js:542)
    at Component.___detach (Component.js:533)
    at morphChildren (index.js:329)
    at morphEl (index.js:790)
    at morphChildren (index.js:384)
    at morphEl (index.js:790)
    at morphChildren (index.js:384)
    at morphEl (index.js:790)
    at morphChildren (index.js:384)
    at morphEl (index.js:790)
```

To isolate this bug, I made a repo so you can easily reproduce this bug: https://github.com/abiyasa/marko-dom-node-bugs

Steps to reproduce:

1. Clone https://github.com/abiyasa/marko-dom-node-bugs and do `yarn install`
1. `yarn start` to start server
1. open http://localhost:8080/bug-dialog-close
1. Click the big blue button to show the dialog.
1. Close the dialog by clicking 'Yes' or 'No' button.
1. Show the dialog again by clicking the big blue button.
1. Checkout the browser console

### Expected Behavior

The dialog should be displayed the 2nd time without any error.

### Actual Behavior

Errors appear on browser's console when trying to display the dialog for the 2nd time. This error breaks the page since any component stop working afterwards (until you refresh the page).

### Possible Fix

The cause is unknown but if we close the dialog by clicking 'X' button on dialog's top corner (or clicking outside the dialog area), the error does NOT appear!

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js 8.11.x, Latest Chome & Firefox
* Operating System and version (desktop or mobile): OSX
* Link to your project: https://github.com/abiyasa/marko-dom-node-bugs

### Steps to Reproduce

1. Clone https://github.com/abiyasa/marko-dom-node-bugs and do `yarn install`
1. `yarn start` to start server
1. open http://localhost:8080/bug-dialog-close
1. Click the big blue button to show the dialog.
1. Close the dialog by clicking 'Yes' or 'No' button.
1. Show the dialog again by clicking the big blue button.
1. Checkout the browser console

### Stack Trace

```
Uncaught TypeError: Cannot read property 'nextSibling' of null
    at Component.___forEachNode (Component.js:542)
    at Component.___detach (Component.js:533)
    at morphChildren (index.js:329)
    at morphEl (index.js:790)
    at morphChildren (index.js:384)
    at morphEl (index.js:790)
    at morphChildren (index.js:384)
    at morphEl (index.js:790)
    at morphChildren (index.js:384)
    at morphEl (index.js:790)
```

</details>

### LINKED ISSUE #1059: DOM Exceptions and rendering issues
### Marko Version: x.x.x

    "marko": "4.10.0",
    "marko-loader": "1.3.3",

### Details

I have a marko powered isomorphic webapp in the works (nearing staging) and are running into some critical DOM issues that come up from time to time.  Reproducing them in a standalone project has been a difficult task, and I am yet to reproduce them all.

However I have managed to produce three different bugs, which I have bundled together in a single issue as I suspect they are related.  I can split them up if need be.

####  1: a `<html-comment>` tag is viewable on screen
 - not critical as I can just remove the html-comment tag however I think it may be related to the other bugs, or indicative that something is broken in how marko identifies components using html comment dom nodes.

#### 2: DOMException

```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insertBefore (http://localhost:3001/static/bundle.js:2056:23)
    at morphChildren (http://localhost:3001/static/bundle.js:2351:25)
    at morphEl (http://localhost:3001/static/bundle.js:2813:13)
    at morphChildren (http://localhost:3001/static/bundle.js:2407:29)
    at morphEl (http://localhost:3001/static/bundle.js:2813:13)
    at morphChildren (http://localhost:3001/static/bundle.js:2407:29)
    at morphComponent (http://localhost:3001/static/bundle.js:2178:9)
    at morphChildren (http://localhost:3001/static/bundle.js:2369:44)
    at morphdom (http://localhost:3001/static/bundle.js:2822:5)
    at http://localhost:3001/static/bundle.js:6675:13
```

#### 3: Include/Transclude Bug

DOM nodes dissapear from the document when interacting with a sibling element

This may be related to a previous bug I submitted https://github.com/marko-js/marko/issues/1022 as the trigger (forceUpdate or state change) is the same however  but the effect of the bug is different

#### : 4 - Not yet able to reproduce in isolation

```
Uncaught TypeError: Cannot read property 'insertBefore' of null
    at insertBefore (index.js?8192:33)
    at morphComponent (index.js?8192:148)
    at morphChildren (index.js?8192:346)
    at morphdom (index.js?8192:799)
    at eval (Component.js?2cba:516)
    at Object.batchUpdate [as ___batchUpdate] (update-manager.js?8c0e:63)
    at Component.___rerender (Component.js?2cba:499)
    at Component.update (Component.js?2cba:452)
    at updateComponents (update-manager.js?8c0e:44)
    at updateUnbatchedComponents (update-manager.js?8c0e:16)
    at eval (nextTick-browser.js?bdf1:18)
    at wrapped (raven.js?8d3d:377)
```
From debugging it appears that in Component.js ___forEachNode :
I've ran in to various combinations of 
* this.___startNode.parentNode is null and this.___endNode.parentNode is null
* this.___startNode.parentNode is not = this.___endNode.parentNode
* this.___startNode is null
* this.___endNode is null
very strange

__
### Possible Fix

For bug (2) I have provided three demonstrations of how to change your marko code to work around the bugs

### Your Environment
```
"browser-refresh-taglib": "^1.1.0",
"express": "^4.14.0",
"marko": "^4.10.0",
"marko-loader": "^1.3.3",
"query-string": "^6.1.0",
"serve-static": "^1.11.1",
"webpack": "^2.6.1",
"webpack-dev-server": "2.9.3"

"@babel/core": "^7.0.0-beta.42",
"@babel/preset-env": "^7.0.0-beta.42",
"@babel/register": "^7.0.0-beta.42",
"babel-loader": "8.0.0-beta.2"
```

see package.json / yarn.lock at https://github.com/cameronbraid/marko-dom-issue/

### Steps to Reproduce

git clone https://github.com/cameronbraid/marko-dom-issue/
yarn
yarn devserver
yarn server
google-chrome http://localhost:8180

The follow the on screen instructions

### PR DESCRIPTION
**Pull request by mlrawlings**
## Description

The infamous `nextSibling` error is caused by trying to reuse a component that has been removed from the DOM, but not removed from the global component lookup.

```
TypeError: Cannot read property 'nextSibling' of null
      at Component.___forEachNode (src/components/Component.js:542:43)
      at Component.___detach (src/components/Component.js:533:14)
      ...
```

This PR does two things _(updated)_:

- Skips over a component when removing remaining DOM nodes, and if the component is not in the current render lookup, it is now destroyed.
- When recursively destroying nodes, the top level node now also destroys its associated component (in `destroyNodeRecursive`).

## Motivation and Context
Fixes #1059 and #1052

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated/added documentation affected by my changes.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the project's open source license and warrant that you have the legal authority to do so._

### CODE REVIEW

**Comment by mlrawlings** [comment]
Thanks to @abiyasa, @cameronbraid, and @BryceEWatson for their help in tracking down this issue. 🙂

**Comment by jasonmacdonald** [comment]
Does this also fix https://github.com/marko-js/marko/issues/947 ?

**Comment by mlrawlings** [comment]
@jasonmacdonald Unfortunately I don't think so. 😞 

AFAIK, we don't have a test case for that issue yet.

**Comment by jasonmacdonald** [comment]
hmm, that ticket is also the result of global lookup not being cleaned. That's why I thought this may address it as well. I can dream I guess lol. I'll look to add a test case for that then.

**Comment by BryceEWatson** [comment]
@mlrawlings yay!
@cameronbraid created a test case in this PR https://github.com/marko-js/marko/pull/1064 , does this fix work in that case?

**Comment by cameronbraid** [comment]
@merwan7 thank you, i'll do some testing against this PR

**Comment by cameronbraid** [comment]
I also applied the changes in morphdom/index.js to my demo app for issue https://github.com/marko-js/marko/issues/1059 and the error still happened

**Pull request merged**
