### PR TITLE
Stream without a context provided (fix exception to undefined variable)

### PR DESCRIPTION
**Pull request by jsumners**
## Description

```js
var template = require('some.marko')
template.stream() // exception on line 234 of runtime/marko-runtime.js
```

## Motivation and Context

Fixes a runtime exception when streaming without providing a data context.

I would provide a test for this, but I can't find where it would go or any tests that resemble the case to emulate.

### CODE REVIEW

**Comment by austinkelleher** [comment]
I think a test for this should live in `test/autotests/api`. An example is: `test/autotests/api/require-render-to-stream`.

**Comment by jsumners** [comment]
@austinkelleher thanks. I added the test.

**Comment by austinkelleher** [comment]
Also, the API has changed in v4, and I don't think this is an issue anymore, but I think this change should be back ported to v3.

**Comment by jsumners** [comment]
@austinkelleher I wrote this against the v3 branch. It is a bug that is impacting my current usage of Marko.

**Comment by austinkelleher** [comment]
LGTM /cc @mlrawlings

**Comment by austinkelleher** [comment]
Actually I have a small suggestion after reviewing the code in v4. What do you think about changing the implementation to be more uniform with the v4 implementation?

https://github.com/marko-js/marko/blob/master/runtime/stream.js#L40

**Comment by mlrawlings** [comment]
I like it.  Thanks @jsumners and @austinkelleher!

**Comment by mlrawlings** [comment]
@jsumners Just published `marko@3.12.1`

**Comment by jsumners** [comment]
@mlrawlings thank you.

**Pull request merged**
