### PR TITLE
Fixes top level static for custom tags.

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
Using `lasso-resource` seems to wrap a top level template in a `CustomTag` instead of `TemplateRoot` breaking the `static` tag. This change allows for the `static` tag in this case.

EDIT: This is now fixed by pulling out the code in the `static` tag before other transformers run.

## Motivation and Context
https://github.com/marko-js/marko/issues/926

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated/added documentation affected by my changes.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Not quite sure the best way to test this in the project (although it works in manual testing with marko-starter).

@austinkelleher @mlrawlings any ideas?

**Comment by DylanPiercey** [comment]
@austinkelleher please read my comment 😅

**Comment by austinkelleher** [comment]
@DylanPiercey You could mock the `lasso-resource` functionality by creating a custom transform that wraps the top level element in a `CustomTag` as part of your test.

**Comment by mlrawlings** [comment]
I would maybe rename the test to `static-tag-wrap-all-children` or something that better explains the test, but otherwise looks good.

**Pull request merged**
