### PR TITLE
Adding assign tag

### PR DESCRIPTION
**Pull request by BryceEWatson**
For issue https://github.com/marko-js/marko/issues/171
Adds assign tag compiler, taglib, and test files.
The compiler uses `builder.assignment()` to write one or more assignments.

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
Hey Bryce, thanks for the PR. What you submitted will work, but let's avoid introducing a new `Assign` AST node since it will confuse things (there is already an `Assignment` AST node). Instead, let's use the `codeGenerator(elNode, generator)` API for the custom tag to generate an array of assignment expressions. Something like the following should work:

```javascript
module.exports = function codeGenerator(elNode, generator) {
    var builder = generator.builder;

    return elNode.attributes.map((attr) => {
        return builder.assignment(attr.name, attr.value);
    });
};
```

As an example, the `<for>` tag uses the code generator API: https://github.com/marko-js/marko/blob/htmljs-parser/taglibs/core/for-tag.js

Instead of using `"node-factory"` in the `taglibs/core/marko-taglib.json` you should use do the following:

```json
"code-generator": "./assign-tag"
```

Also note, I submitted a bunch of changes to the `htmljs-parser` branch. Please make sure you pull in all of the latest changes! Thanks again!

**Comment by patrick-steele-idem** [comment]
Hey @BryceEWatson, just wanted to check in and see if you had some time to try implementing the `<assign>` tag with the `code-generator` API. Please let me know if you would like more details. Thanks.

**Comment by BryceEWatson** [comment]
Hi @patrick-steele-idem, I notice that Assignment does not add semi-colons or new lines. Assuming I'll just add those in the tag file instead? Or would this be something to add into the Assignment builder?

**Comment by patrick-steele-idem** [comment]
The AST Nodes do not need to write out the semicolons. That gets handled by the `generateStatements()` method: 
https://github.com/marko-js/marko/blob/2a34d940e47e7617361ea7d7893927a46580d522/compiler/CodeGenerator.js#L289-L291

If you just return an array of assignment nodes then everything should work as expected, but please verify.

**Comment by BryceEWatson** [comment]
Thanks @patrick-steele-idem, I've included your suggestion & squashed the commit. Let me know if there's any other improvements you see.

**Comment by patrick-steele-idem** [comment]
Looks great. Glad everything works with less code. Thanks!

Let me know if you are interested in taking on the `<include>` tag next: https://github.com/marko-js/marko/issues/178

**Pull request merged**
